---
apiVersion: v1
kind: Service
metadata:
  name: notes-app
  labels:
    app: notes-app
  spec:
    type: NodePort
    selector:
      app: notes-app
    port:
      - protocol: TCP
        port: 8080
        name: http

---
apiVersion: